### ISSUE TITLE
Project bar not showing

### ISSUE THREAD

**Issue by TigersWay** [cakecatz/flex-toolbar#107]
Hi,
Cannot succeed to get every time the "project part" of the tool-bar.
With Atom 1.16.0 & Windows 7, 
I have with some projects a <toolbar.cson> file n the project root, which allows to add some specific tools. When it's working, everything is fine. But the addon part does not appear without faking 1, sometimes 2 modifications of the config file <toolbar.cson>.
Thanks

**Comment by UziTech** [comment]
Closing as stale.

If this is still an issue feel free to let us know.

**Comment by TigersWay** [comment]
Sorry @UziTech

I'm still using quite a lot this feature, and still having one little trouble. The project part of the flex-bar does only appear when focus is on editing any file of the current project. A click on the tree-view makes it disappear momentarily.
Not a real big trouble, but still :-)

**Comment by UziTech** [comment]
I see, so when you click on the tree view the project tool bar disappears.

This is actually supposed to happen. The project toolbar is for when you are editing a file in that project. When you click on the tree view, settings, or any other dock item, the focus is moved away from the current project file so the tool bar disappears.

I could add a setting to make the project toolbar persistent so it would just check the project paths instead of the focused editor. Would that solve your problem?

**Comment by UziTech** [comment]
Or would you only want it to stay if the tree view is focused?

**Comment by TigersWay** [comment]
I get your point :-)
Well, I'm just and only 1 user....  But yes, I would love to be able to keep it visible while on that project whatever I'm doing in it, browsing around or editing.

> I could add a setting to make the project toolbar persistent so it would just check the project paths instead of the focused editor. Would that solve your problem?

That would be really nice!

> Or would you only want it to stay if the tree view is focused?

I'm pretty sure I would then discover another "focus" somewhere else!

Thanks for the work anyway!
