### ISSUE TITLE
Add hook to grammar change

### ISSUE THREAD

**Issue by StaticRocket** [cakecatz/flex-toolbar#136]
Script a toolbar refresh to occur when the tab grammar is changed so single tab projects get their required toolbar without having the user make a new tab, switch to it, and switch back to refresh the toolbar manually.

Based on the issue I have when I change the grammar the toolbar does not update to show grammar specific buttons until I switch to another tab and switch back. If this is already a feature, sorry for the pointless request. If it is a bug and it should be updating immediately any help is appreciated.

**Comment by StaticRocket** [comment]
It may also be worth mentioning that the buttons also disappear if one clicks on any side panels, such as the project explorer or git panels. This occurs with or without "Persistent Project Tool Bar" being toggled.

**Comment by UziTech** [comment]
If the button is set to `show: "Some Grammar"` than clicking on a side panel will change the grammar to `null` and hide the button since the active item changed to the panel that you clicked on. This is the intended behavior.

Some panels, like the find/replace panel, won't change the active item so the grammar should not change.

Changing the grammar should be working in the newest release. If you still think the buttons disappearing is a bug please open a new issue.

**Comment by StaticRocket** [comment]
Right, I had suspected it was grabbing null grammer from side panels. I suppose it isn't that much of a problem, I just need to be aware of moving elements. Good job patching the original ticket issue, I will be testing that soon enough.
