### ISSUE TITLE
CSON,JSON5 support

### ISSUE THREAD

**Issue by cakecatz** [cakecatz/flex-toolbar#16]
Current config file type is `json`, but it is not good for me.
I want to add support other config file type like `.cson`, `.json5`.

**Comment by jerone** [comment]
:+1: This will allow comments in the toolbar file.

**Comment by varemenos** [comment]
:+1: plus it will add some consistency to the configuration files, having half the files in JSON and the rest in CSON is somewhat confusing

**Comment by jerone** [comment]
Is it an idea to only use the path from the setting `toolBarConfigurationJsonPath`?  Thus no filename and extension, like the name says.

That way it would be possible to search for alternative toolbar file extensions. So that if no `toolbar.json` is created in the root, it will look for a CSON file and if not found the JSON5 file?

I created a CSON file and deleted my toolbar.json file, which resulted in errors as it was searching for the default file (`toolBarConfigurationJsonPath`). I hoped it looked for the second alternative `toolbar.cson`.

**Comment by jerone** [comment]
Working now! :+1: 

Wondering what the performance impact is in checking for every extension...
Does Atom allow `.json` and `.json5` files too for their `config.cson`, `init.cson`, `keymap.cson`, `snippets.cson` and `styles.cson`?

**Comment by cakecatz** [comment]
> Wondering what the performance impact is in checking for every extension...

I'll rewrite code using `fs.resolve` soon.
It's maybe good performance.

Atom doesn't allow `json5`, but `json` is allowed.
I found [this](https://github.com/atom/atom/blob/2921a4cd1fecc85adaa7db48371fdf6b07372904/src/config.coffee#L332).
